### ISSUE TITLE
Are `as` and `class` working?

### ISSUE THREAD

**Issue by RicardoValero95** [rgossiaux/svelte-headlessui#33] opened 2022-01-07 20:38 UTC
I'm using Windi CSS with Svelte Kit.

Most of the things work and are straight forward, but using the components I can't use the `as` and `class` props.
So I need to nest a `div` or other html element. Is this intended? 

A port from the headless ui react example 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/55701657/148603378-75e3d007-cc01-4051-9312-d4d2b5828884.png">

```svelte
<script>
	import {
		RadioGroup,
		RadioGroupDescription,
		RadioGroupLabel,
		RadioGroupOption
	} from '@rgossiaux/svelte-headlessui';

	const plans = [
		{
			name: 'Startup',
			ram: '12GB',
			cpus: '6 CPUs',
			disk: '160 GB SSD disk'
		},
		{
			name: 'Business',
			ram: '16GB',
			cpus: '8 CPUs',
			disk: '512 GB SSD disk'
		},
		{
			name: 'Enterprise',
			ram: '32GB',
			cpus: '12 CPUs',
			disk: '1024 GB SSD disk'
		}
	];

	let value = plans[0];
</script>

<div class="w-full px-4 py-16">
	<div class="w-full max-w-md mx-auto">
		<RadioGroup {value} on:change={(e) => (value = plans.find((p) => p.name === e.detail.name))}>
			<RadioGroupLabel>
				<div class="sr-only">Server size</div>
			</RadioGroupLabel>
			<div class="space-y-2">
				{#each plans as plan (plan.name)}
					<RadioGroupOption key={plan.name} value={plan} let:active let:checked>
						<div
							class={`
                            relative rounded-lg shadow-md px-5 py-4 cursor-pointer flex focus:outline-none 
                            ${checked ? 'bg-sky-900 bg-opacity-75 text-white' : 'bg-white'} ${
								active ? 'ring-2 ring-offset-2 ring-offset-sky-300 ring-white ring-opacity-60' : ''
							} 
                            `}
						>
							<div class="flex items-center justify-between w-full">
								<div class="flex items-center">
									<div class="text-sm">
										<RadioGroupLabel>
											<p class={`font-medium ${checked ? 'text-white' : 'text-gray-900'}`}>
												{plan.name}
											</p>
										</RadioGroupLabel>
										<RadioGroupDescription>
											<span class={`inline ${checked ? 'text-sky-100' : 'text-gray-500'}`}>
												<span>
													{plan.ram}/{plan.cpus}
												</span>
												<span aria-hidden="true">&middot;</span>{' '}
												<span>{plan.disk}</span>
											</span>
										</RadioGroupDescription>
									</div>
								</div>
								{#if checked}
									<div class="flex-shrink-0 text-white">
										<svg class="w-6 h-6" viewBox="0 0 24 24" fill="none">
											<circle cx={12} cy={12} r={12} fill="#fff" opacity="0.2" />
											<path
												d="M7 13l3 3 7-7"
												stroke="#fff"
												stroke-width={1.5}
												stroke-linecap="round"
												stroke-linejoin="round"
											/>
										</svg>
									</div>
								{/if}
							</div>
						</div>
					</RadioGroupOption>
				{/each}
			</div>
		</RadioGroup>
	</div>
</div>

```

**Comment by rgossiaux** [comment] 2022-01-07 21:39
Thanks for the report! Very helpful. I was able to reproduce the two issues I think you're talking about:

* `as` for labels is not working. This is a bug; it's because the Label component isn't using the `<Render>` component when it should be: https://github.com/rgossiaux/svelte-headlessui/blob/5d83d35e715f965119cf0f71231bfc430dea3250/src/lib/components/label/Label.svelte#L21
* `class` for labels is not reactive. This is also a bug; this line should be reactive: https://github.com/rgossiaux/svelte-headlessui/blob/5d83d35e715f965119cf0f71231bfc430dea3250/src/lib/components/label/Label.svelte#L16

I think Labels didn't get as much testing because they're a separate component from the "main" components + the upstream library doesn't really have many tests for them. I'll try to add some more unit tests with the fixes. The `as` and `class` props do work in general, eg they work correctly for the RadioGroupDescription in the same example.

I'm pretty busy today but I hope to fix this over the weekend.

**Comment by RicardoValero95** [comment] 2022-01-07 22:45
Don't worry take your time, you've done great work. 

I saw you mentioned [Svelte Material UI](https://github.com/hperrin/svelte-material-ui), maybe more inspiration can be drawn from [Renderless Svelte](https://github.com/stephane-vanraes/renderless-svelte) and [Carbon Components Svelte](https://github.com/carbon-design-system/carbon-components-svelte)

**Comment by rgossiaux** [comment] 2022-01-20 23:06
Thanks for the report! This will be fixed in the next release later today.

**Closed** 2022-01-20 23:05 UTC
