### ISSUE TITLE
Popover inside tab panel closes on inner click

### ISSUE THREAD

**Issue by vkurko** [rgossiaux/svelte-headlessui#91] opened 2022-05-05 13:05 UTC
**Describe the bug**
When the popover is located inside a tab panel, clicking anywhere INSIDE of its contents closes the popover.

**To Reproduce**
[REPL](https://svelte.dev/repl/f405bcb5222a4acc9b9537158391c489?version=3.48.0)

**Library version**
1.0.0-beta.12

**Comment by vkurko** [comment] 2022-05-05 13:09
Hopefully this ticket won't be closed before the issue is resolved.

**Comment by rgossiaux** [comment] 2022-05-06 19:02
Thanks for the report. This is because a TabPanel is focusable, so clicking on a Popover that's inside a TabPanel will focus the TabPanel (which surrounds, and thus is outside of, the Popover). The Popover has logic to close itself when focus leaves the Popover and this is the result.

Here's a similar issue in upstream: https://github.com/tailwindlabs/headlessui/issues/1007

The workaround is probably clear from this description, but it's also mentioned in that linked issue: you need to make your `PopoverPanel` focusable, by eg applying a `tabIndex` of `-1`.

Hope this helps. Since this is, at the moment, intended behavior, I'm closing this.

**Closed by rgossiaux** 2022-05-06 19:02 UTC
