### ISSUE TITLE
Output noise for "unused export properties" makes it hard to read other useful information

### ISSUE THREAD

**Issue by mattcroat** [rgossiaux/svelte-headlessui#84] opened 2022-03-24 19:30 UTC
Hey! 👋

Thank you for your work on this wonderful project.

I have a concern with the output noise whenever I run the project using `pnpm run dev` or build using `pnpm run build` that makes it hard to read other useful information.

<details>
  <summary>Output</summary>

```
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/dialog/Dialog.svelte:2:11 Dialog has unused export property 'DialogStates'. If it is for external reference only, please consider using `export const DialogStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/listbox/Listbox.svelte:1:37 Listbox has unused export property 'ListboxStates'. If it is for external reference only, please consider using `export const ListboxStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/disclosure/Disclosure.svelte:3:11 Disclosure has unused export property 'DisclosureStates'. If it is for external reference only, please consider using `export const DisclosureStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/popover/Popover.svelte:1:37 Popover has unused export property 'PopoverStates'. If it is for external reference only, please consider using `export const PopoverStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/menu/Menu.svelte:9:11 Menu has unused export property 'MenuStates'. If it is for external reference only, please consider using `export const MenuStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:21:11 Render has unused export property 'RenderStrategy'. If it is for external reference only, please consider using `export const RenderStrategy`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:3:11 Render has unused export property 'Features'. If it is for external reference only, please consider using `export const Features`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/internal/StackContextProvider.svelte:1:37 StackContextProvider has unused export property 'StackMessage'. If it is for external reference only, please consider using `export const StackMessage`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/transitions/common.svelte:4:11 Common has unused export property 'TreeStates'. If it is for external reference only, please consider using `export const TreeStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/dialog/Dialog.svelte:2:11 Dialog has unused export property 'DialogStates'. If it is for external reference only, please consider using `export const DialogStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/disclosure/Disclosure.svelte:3:11 Disclosure has unused export property 'DisclosureStates'. If it is for external reference only, please consider using `export const DisclosureStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/listbox/Listbox.svelte:1:37 Listbox has unused export property 'ListboxStates'. If it is for external reference only, please consider using `export const ListboxStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/menu/Menu.svelte:9:11 Menu has unused export property 'MenuStates'. If it is for external reference only, please consider using `export const MenuStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/popover/Popover.svelte:1:37 Popover has unused export property 'PopoverStates'. If it is for external reference only, please consider using `export const PopoverStates`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/internal/StackContextProvider.svelte:1:37 StackContextProvider has unused export property 'StackMessage'. If it is for external reference only, please consider using `export const StackMessage`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:21:11 Render has unused export property 'RenderStrategy'. If it is for external reference only, please consider using `export const RenderStrategy`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:3:11 Render has unused export property 'Features'. If it is for external reference only, please consider using `export const Features`
8:00:00 PM [vite-plugin-svelte] /node_modules/.pnpm/@rgossiaux+svelte-headlessui@1.0.0-beta.12_svelte@3.46.4/node_modules/@rgossiaux/svelte-headlessui/components/transitions/common.svelte:4:11 Common has unused export property 'TreeStates'. If it is for external reference only, please consider using `export const TreeStates`
```

</details>

I tried it using both `npm` and `pnpm` and the result is the same. Steps to reproduce are simple using the basic `<Listbox />` example from the documentation.

**Comment by rgossiaux** [comment] 2022-03-24 19:32
Duplicate of #25 

This will be fixed in the next version of Svelte btw, I merged in a PR to fix it. It's a bug in Svelte, nothing else I can do about it.

**Closed by rgossiaux** 2022-03-24 19:32 UTC
